const router = require('express').Router()
const userRoutes = require('./user.routes')
const journalRoutes = require('./journal.routes')
const postRoutes = require('../routes/post.routes')
const timelineRoutes = require('../routes/timeline.routes')
const { checkToken } = require('../middlewares/auth')
const profileRoutes = require('../routes/profile.routes')
const checkApiKey = require('../middlewares/checkApiKey')
router.use('/user', checkApiKey, userRoutes)
router.use('/journal', checkApiKey, checkToken, journalRoutes)
router.use('/post', checkApiKey, checkToken, postRoutes)
router.use('/timeline', checkApiKey, timelineRoutes)
router.use('/profile', checkApiKey, profileRoutes)
module.exports = router
